export interface SupplierData extends Record<string, any> {
  id?: number | null | undefined,
  company_name?: string | null | undefined,
  status?: number | null | undefined,
  put_type?: number | null | undefined,
  approver_id?: number | null | undefined,
  payment_days?: number | null | undefined,
  level?: number | null | undefined,
  business_type_ids?: Array<string | null | undefined>,
  create_time?: Array<string | null | undefined>,
  update_time?: Array<string | null | undefined>,
  approval_time?: Array<string | null | undefined>,
  contacts?: string | null | undefined,
  phonenum?: string | null | undefined,
  email?: string | null | undefined,
  referee?: string | null | undefined,
  remark?: string | null | undefined,
  update_by?: string| null | undefined,
}
export interface SupplierYearData extends Record<string, any> {
  id?: number | null | undefined,
  supplier_id?: number | null | undefined,
  company_name?: string | null | undefined,
  status?: number | null | undefined,
  put_type?: number | null | undefined,
  approver_id?: number | null | undefined,
  payment_days?: number | null | undefined,
  level?: number | null | undefined,
  business_type_map?: string | null | undefined,
  business_type_ids?: Array<string | null | undefined>,
  create_time?: Array<string | null | undefined>,
  update_time?: Array<string | null | undefined>,
  approval_time?: Array<string | null | undefined>,
  media_ids?: Array<string | null | undefined>,
  contract_info?: Array<Record<string, any> | null | undefined>,
  year?: string | null | undefined,
  email?: string | null | undefined,
  referee?: string | null | undefined,
  sign_date?: string | null | undefined,
  sign_by?: string| null | undefined,
  update_by?: string | null | undefined,
  approver?: string | null | undefined,
  approval_remark?: string | null | undefined,
  address?: string | null | undefined,
  build_time?: string | null | undefined,
  business_scope?: string | null | undefined,
  revenue_scale?: string | null | undefined,
  description?: string | null | undefined,
  company_nature?: string | null | undefined,
  registered_capital?: string | null | undefined,
  business_license?: string | null | undefined,
  general_taxpayer_certificate?: string | null | undefined,
  tax_num?: string | null | undefined,
  invoice_title?: string | null | undefined,
  bank_name?: string | null | undefined,
  account_number?: string | null | undefined,
  register_address?: string | null | undefined,
  tel?: string | null | undefined,
  contacts?: string | null | undefined,
  phonenum?: string | null | undefined,
}